### ISSUE TITLE
Not an issue, a quick kubernetes with nginx starting point

### ISSUE THREAD

**Issue by adepssimius** [pbogre/jetlog#30]
Make sure you customize the PVC and the ingress, I'm running this on ceph and nginx. I had to customize the start command to allow this to run rootless and have the PVC work at the same time.

```
apiVersion: v1
kind: Namespace
metadata:
  name: jetlog
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jetlog
  namespace: jetlog
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
  storageClassName: rook-ceph-ssd-block # ATTENTION HERE!
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jetlog
  namespace: jetlog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jetlog
  template:
    metadata:
      labels:
        app: jetlog
    spec:
      containers:
        - name: jetlog
          image: pbogre/jetlog:latest
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: jetlog
              mountPath: /data
          env:
            # - name: JETLOG_PORT
            #   value: "3000"
            - name: DATA_PATH
              value: "/data"
            # - name: PGID
            #   value: "1000"
            # - name: PUID
            #   value: "1000"
          command: [ "python", "-m", "uvicorn", "main:app", "--app-dir", "server", "--host", "0.0.0.0" ] # ATTENTION HERE
      volumes:
        - name: jetlog
          persistentVolumeClaim:
            claimName: jetlog
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
---
apiVersion: v1
kind: Service
metadata:
  name: jetlog
  namespace: jetlog
spec:
  selector:
    app: jetlog
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jetlog
  namespace: jetlog
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: jetlog.your-domain.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: jetlog
                port:
                  number: 80
```
